# serverless.yml

service: postit-api
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: sa-east-1
functions:
  graphql:
    handler: index.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
