# serverless.yml

service: postit-apo
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: sa-east-1
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: index.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true