type Usuario{
    id: Int
    nome: String
    email: String
    produtos: String
}

input UsuarioInput {
    nome: String
    email: String
    produtos: String
}

type Query{
    usuarios: [Usuario]
}

type Mutation{
    criarUsuario(data: UsuarioInput): Usuario
}